import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

Bundles @defaultusr/vertical-timeline (MIT) and d3-scale (ISC).
*/
`;

const mode = process.argv[2]; // "production", "harness" or nothing (watch)
const prod = mode === "production";

const harness = {
	entryPoints: ["harness/harness.ts"],
	outfile: "harness/harness.js",
	format: "iife",
	alias: { obsidian: "./harness/obsidian-mock.ts" },
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	...(mode === "harness" ? { ...harness, external: [] } : {}),
});

if (prod || mode === "harness") {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
